# Generated by Django 5.2.6 on 2025-10-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="publication_sign",
            new_name="is_published",
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="article",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cчетчик просмотров"
            ),
        ),
    ]
