# Generated by Django 5.2.6 on 2025-09-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='catalog/image', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Введите цену продукта', verbose_name='Цена')),
                ('created_at', models.DateField(help_text='Введите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateField(help_text='Введите дату последнего изменения', verbose_name='Дата последнего изменения')),
                ('category', models.ForeignKey(help_text='Введите категорию продукта', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name', 'price'],
            },
        ),
    ]
